version: '3.6'

services:
  web:
    container_name: web
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: bundle exec puma
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres@postgres
      REDIS_URL: redis://redis:6379/0

  postgres:
    container_name: postgres
    image: postgres:10.7-alpine
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    container_name: redis
    image: 'redis:4.0-alpine'
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - 'redis:/data'

volumes:
  redis:
  postgres: