version: 2
jobs:
  build:
    working_directory: ~/Plantia/plantia-web
    parallelism: 2
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: plantia_test
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:10.5-alpine
        environment:
          POSTGRES_USER: plantia_test
          POSTGRES_DB: plantia_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Bundler
      - restore_cache:
          keys:
            - plantia-bundle-{{ checksum "Gemfile.lock" }}
            - plantia-bundle-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: plantia-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # NPM & Node Modules
      - restore_cache:
          key: plantia-npm-{{ checksum "package.json" }}

      - run:
          name: npm Install
          command: npm install

      - save_cache:
          key: plantia-npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run Rake tests
          command: bundle exec rake test

      # Run rspec in parallel
      - run:
          name: Run rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test-results/rspec.xml \
                              --format progress \
                              --require spec_helper \
                              $(circleci tests glob spec/**/*_spec.rb | circleci tests split)

      # Save test results for timing analysis
      - store_test_results:
          path: test-results